In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("dataset_all_points.csv")

In [4]:
df.head()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z31,v31,x32,y32,z32,v32,x33,y33,z33,v33
0,rest,0.577706,0.231914,-0.420472,0.999994,0.586725,0.216498,-0.401769,0.999976,0.591864,...,0.295693,0.813606,0.600815,0.954061,0.170028,0.974830,0.549842,0.954096,0.141380,0.972387
1,rest,0.577704,0.232117,-0.423063,0.999993,0.586727,0.216654,-0.403755,0.999974,0.591878,...,0.299121,0.812577,0.599050,0.954614,0.164307,0.974812,0.549786,0.953416,0.145572,0.971996
2,rest,0.577799,0.232135,-0.422215,0.999994,0.586800,0.216666,-0.402409,0.999974,0.591967,...,0.293218,0.811234,0.598365,0.955232,0.153990,0.974692,0.549756,0.952766,0.141057,0.971638
3,rest,0.577943,0.231958,-0.410397,0.999994,0.586904,0.216641,-0.389879,0.999974,0.592074,...,0.286550,0.810070,0.598157,0.955507,0.146956,0.974607,0.549752,0.952397,0.134446,0.971380
4,rest,0.578053,0.231574,-0.407048,0.999993,0.586976,0.216544,-0.386019,0.999974,0.592150,...,0.283523,0.808028,0.597895,0.955590,0.148918,0.974572,0.549865,0.952053,0.129813,0.971095